remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme


title: [Burp Bambdas Cheatsheet]
description: [A open project that list all the community shared burp bamdbas to directly copy and use them]